// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf/erutan.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Erutan {
  /// <summary>
  ///
  ///The Erutan service.
  /// </summary>
  public static partial class Erutan
  {
    static readonly string __ServiceName = "erutan.Erutan";

    static readonly grpc::Marshaller<global::Erutan.Packet> __Marshaller_erutan_Packet = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Erutan.Packet.Parser.ParseFrom);

    static readonly grpc::Method<global::Erutan.Packet, global::Erutan.Packet> __Method_Stream = new grpc::Method<global::Erutan.Packet, global::Erutan.Packet>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Stream",
        __Marshaller_erutan_Packet,
        __Marshaller_erutan_Packet);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Erutan.ErutanReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Erutan</summary>
    [grpc::BindServiceMethod(typeof(Erutan), "BindService")]
    public abstract partial class ErutanBase
    {
      public virtual global::System.Threading.Tasks.Task Stream(grpc::IAsyncStreamReader<global::Erutan.Packet> requestStream, grpc::IServerStreamWriter<global::Erutan.Packet> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Erutan</summary>
    public partial class ErutanClient : grpc::ClientBase<ErutanClient>
    {
      /// <summary>Creates a new client for Erutan</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ErutanClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Erutan that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ErutanClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ErutanClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ErutanClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Erutan.Packet, global::Erutan.Packet> Stream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Stream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Erutan.Packet, global::Erutan.Packet> Stream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Stream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ErutanClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ErutanClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ErutanBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Stream, serviceImpl.Stream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ErutanBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Stream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Erutan.Packet, global::Erutan.Packet>(serviceImpl.Stream));
    }

  }
}
#endregion
